fragment SiteParts on Site {
  __typename
  meta {
    __typename
    title
    description
  }
  nav {
    __typename
    brand
    subbrand
    cta_secondary
    cta_primary
  }
  hero {
    __typename
    tag
    title
    title_highlight
    description
    cta_primary
    cta_secondary
    badge1
    badge2
  }
  value {
    __typename
    tag
    title
    title_highlight
    description
    link_text
    features {
      __typename
      icon
      title
      desc
    }
  }
  servicios {
    __typename
    tag
    title
    title_highlight
    description
    footer_text
    footer_link
    tabs {
      __typename
      id
      icon
      label
      planes {
        __typename
        nombre
        icon
        precio
        periodo
        desc
        popular
        features {
          __typename
          text
          included
        }
      }
    }
  }
  porque {
    __typename
    tag
    title
    title_highlight
    description
    founder_name
    founder_role
    features {
      __typename
      icon
      title
      desc
    }
  }
  stats {
    __typename
    target
    suffix
    label
  }
  portafolio {
    __typename
    tag
    title
    title_highlight
    items {
      __typename
      categoria
      titulo
      color1
      color2
      icon
    }
  }
  testimonios {
    __typename
    tag
    title
    title_highlight
    items {
      __typename
      texto
      nombre
      rol
      iniciales
    }
  }
  nosotros {
    __typename
    tag
    title
    title_highlight
    descripcion1
    descripcion2
    fundacion
    paises
    clientes
    equipo {
      __typename
      nombre
      rol
      iniciales
    }
  }
  faq {
    __typename
    tag
    title
    title_highlight
    items {
      __typename
      pregunta
      respuesta
    }
  }
  contacto {
    __typename
    tag
    title
    title_highlight
    subtitulo
    telefono
    email
    ubicacion
    horario
    badge_title
    badge_desc
    servicios_form
  }
  cta {
    __typename
    tag
    title
    title_highlight
    description
    cta_primary
    cta_secondary
  }
  footer {
    __typename
    tagline
    copyright
  }
}
